os: linux
dist: focal
language: python

python: "3.7"

addons:
  apt:
    packages:
    - libcups2-dev

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install flake8-per-file-ignores
  - pip install coveralls

before_script:
  - flake8 edc_label

script:
   - coverage run --source=edc_label manage.py test

after_success:
- coveralls
